name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this if your main branch is different

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'  # Specify the Node.js version if needed
        displayName: 'Install Node.js'

      - checkout: self  # Checkout the repository's code
        displayName: 'Checkout code'

      - script: |
          echo "No build step required for static HTML/CSS"
        displayName: 'No Build Required'

      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: '$(deployment_token)'  # Set this in GitHub Secrets
          app_location: '/'  # The location of your app's source code
          output_location: ''  # No build output location for static files
